config/routes.rb
Rails.application.routes.draw do
  root to: "root#index"

  resources :cards
  post "cards/ocr", format: "json", to: "cards#ocr", as: "card_ocr"
  resources :companies, except: [ :destroy ]
  get "api/postcode", format: "json", to: "api#postcode", as: "poostcode"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  enum category: { ltd: 0x00, llc: 0x01, limited: 0x02, foundation: 0x10, university: 0x20 }
  enum category_position: { non: 0, before: 1, after: 2 }
  image_field :logo_image
  has_many :cards

  validates :name, presence: true
  validates :short_name, presence: true
  validates :kana_name, presence: true
  validates :category, presence: true
  validates :category_position, presence: true

  before_save :set_color

  def formal_name
    case category_position.intern
    when :before
      self.class.human_attribute_name(category, locale: :ja) + name
    when :after
      name + self.class.human_attribute_name(category, locale: :ja)
    else
      name
    end
  end

  def omit_name
    case category_position.intern
    when :before
      self.class.human_attribute_name("omit_#{category}", locale: :ja) + short_name
    when :after
      short_name + self.class.human_attribute_name("omit_#{category}", locale: :ja)
    else
      short_name
    end
  end

  private

  def set_color
    if logo_image_changed?
      if logo_image
        image_annotate = GoogleApi::ImageAnnotate.new(logo_image.data)
        self.color = (image_annotate.get_properties.dominant_colors.first.hex rescue nil)
      else
        self.color = nil
      end
    end
    self
  end
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.order(:kana_name)
  end

  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to companies_path, notice: t(".successfully_created") }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to companies_path, notice: t(".successfully_updated") }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_company
    @company = Company.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def company_params
    params.require(:company).permit(:name, :short_name, :kana_name, :en_name, :category, :category_position, :logo_image, :note, :web_site)
  end
end

app/helpers/companies_helper.rb
# frozen_string_literal: true

module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company,
              auto_init: true,
              local: true,
              builder: MdcFormHelper::MdcFormBuilder) do |form| %>
  <% if company.errors.any? %>
    <div class="res-error-explanation">
      <p class="mdc-typography--headline6 res-error-explanation__result">
        <%= t("errors.template.header", count: company.errors.count, model: Company.model_name.human) %>:
      </p>
      <ul class="res-error-explanation__message-list">
    <% company.errors.full_messages.each do |message| %>
        <li class="res-error-explanation__message-item"><%= message %></li>
    <% end %>
      </ul>
    </div>
  <% end %>
  <div class="res-field">
    <%= form.text_field :name, required: true, maxlength: 255 %>
  </div>
  <div class="res-field">
    <%= form.text_field :short_name, required: true, maxlength: 31 %>
  </div>
  <div class="res-field">
    <%= form.text_field :kana_name, required: true, maxlength: 255 %>
  </div>
  <div class="res-field">
    <%= form.text_field :en_name, maxlength: 255 %>
  </div>
  <div class="res-field">
    <%= form.select :category, Company.categories.keys.map{|key| [Company.human_attribute_name(key), key]}, { box: true }, { required: true } %>
    <%= form.select :category_position, Company.category_positions.keys.map{|key| [Company.human_attribute_name(key), key]}, { box: true }, { required: true } %>
  </div>
  <div class="res-field">
    <%= form.image_field :logo_image, max_height: 192, accept: "image/png, image/jpeg, image/gif" %>
  </div>
  <div class="res-field">
    <%= form.text_field :web_site, maxlength: 255 %>
  </div>
  <div class="res-field">
    <%= form.text_field :note, maxlength: 255 %>
  </div>
  <div class="res-actions">
    <%= mdc_link_to t("helpers.button.cancel"), {action: :index}, auto_init: true %>
    <%= form.submit raised: true, class: "res-button--raised--secondary" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h2 class="mdc-typography--headline5 res-content-title"><%= t(".edit_company")%></h2>

<div class="res-form-container">
  <%= render 'form', company: @company %>
</div>

app/views/companies/index.html.erb
<h2 class="mdc-typography--headline5 res-content-title"><%= t(".company_settings")%></h2>

<div class="res-content content-companies">
  <div class="res-content-area">
    <div class="mdc-list-group res-content-list res-companies-list">
      <%= mdc_divided_list @companies, :kana_name, :kana, avatar_list: true do |company| %>
        <li class="mdc-list-item res-companies-item" data-company-url="<%= company_path(company, format: :json) %>" data-company-id="<%= company.id %>">
        <% if company.logo_image.present? %>
          <%= base64_image_tag company.logo_image, height: 36, alt: "logo", title: company.omit_name, class: "mdc-list-item__graphic res-company-item__logo" %>
        <% else %>
          <i class="material-icons mdc-list-item__graphic res-company-item__logo" aria-hidden="true" title="<%= company.omit_name %>">business</i>
        <% end %>
          <%= company.formal_name %>
        </li>
      <% end %>
    </div>
  </div>
  <div class="mdc-card res-card res-companies-card" style="display:none">
    <div class="mdc-card__media res-card__media">
      <div class="mdc-card__media-content">
        <div class="res-card__media__icon-button-area">
          <%= mdc_icon_button_tag "delete", title: "delete", class: "res-companies-card-delete" %>
          <%= mdc_icon_button_tag "close", title: "close", class: "res-companies-card-close" %>
        </div>
        <div class="res-card__media__title">
          <span class="mdc-typography--headline6 res-company-info__name"></span>
        </div>
      </div>
      <%= mdc_fab_link_to "edit", "#", mini: true, class: "res-card__fab", label: t(".edit_company"), title: t(".edit_company") %>
    </div>
    <div class="res-card__main">
      <ul class="mdc-list mdc-list--non-interactive res-list--content">
        <li class="mdc-list-item">
          <i class="material-icons mdc-list-item__graphic" title="<%= Company.human_attribute_name(:kana_name) %>" aria-hidden="true">record_voice_over</i>
          <span class="res-company-info__kana-name"></span>
        </li>
        <li class="mdc-list-item">
          <i class="material-icons mdc-list-item__graphic" title="<%= Company.human_attribute_name(:en_name) %>" aria-hidden="true">language</i>
          <span class="res-company-info__en-name"></span>
        </li>
        <li class="mdc-list-item">
          <i class="material-icons mdc-list-item__graphic" title="<%= Company.human_attribute_name(:web_site) %>" aria-hidden="true">web</i>
          <a class="res-list-item__link res-company-info__web-site" href="#" target="_blank"></a>
        </li>
        <li class="mdc-list-item">
          <i class="material-icons mdc-list-item__graphic" title="<%= Company.human_attribute_name(:note) %>" aria-hidden="true">note</i>
          <span class="res-company-info__note"></span>
        </li>
      </ul>
    </div>
  </div>

  <%= mdc_fab_link_to "add", {action: :new}, class: "res-add-fab res-companies-add-button", label: t(".create_company"), title: t(".create_company") %>

  <div class="mdc-snackbar res-companies-snackbar" data-mdc-auto-init="MDCSnackbar">
    <div class="mdc-snackbar__surface">
      <div class="mdc-snackbar__label res-companies-result" role="status" aria-live="polite"><%= notice %></div>
      <div class="mdc-snackbar__actions">
        <button type="button" class="mdc-button mdc-snackbar__action"></button>
      </div>
    </div>
  </div>
</div>

app/views/companies/new.html.erb
<h2 class="mdc-typography--headline5 res-content-title"><%= t(".create_company")%></h2>

<div class="res-form-container">
  <%= render 'form', company: @company %>
</div>