config/routes.rb
Rails.application.routes.draw do
  root to: "root#index"

  resources :cards
  post "cards/ocr", format: "json", to: "cards#ocr", as: "card_ocr"
  resources :companies, except: [ :destroy ]
  get "api/postcode", format: "json", to: "api#postcode", as: "poostcode"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/card.rb
# frozen_string_literal: true

class Card < ApplicationRecord
  belongs_to :company
  image_field :front_image, :back_image

  validates :name, length: { maximum: 31 }, presence: true
  validates :kana_name, length: { maximum: 63 }, presence: true
  validates :department, length: { maximum: 31 }
  validates :position, length: { maximum: 31 }
  validates :postcode, format: { with: /\A(|\d{3}\-\d{4})\z/ }
  validates :address, length: { maximum: 127 }
  validates :building, length: { maximum: 127 }
  validates :tel, format: { with: /\A(|0[\d\-]{11,14})\z/ }
  validates :cellular_phone, format: { with: /\A(|0[\d\-]{11,14})\z/ }
  validates :fax, format: { with: /\A(|0[\d\-]{11,14})\z/ }
  validates :mail, format: { with: /\A(|[\w+\-.]+@[a-z\d\-.]+\.[a-z]+)\z/ }, length: { maximum: 255 }
  validates :qualification, length: { maximum: 255 }
  validates :note, length: { maximum: 255 }
end

app/controllers/cards_controller.rb
# frozen_string_literal: true

class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.includes(:company).order(:kana_name)
    @companies = @cards.map { |card| card.company }.uniq.sort { |a, b| a.kana_name <=> b.kana_name }
  end

  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to cards_path, notice: t(".successfully_created") }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to cards_path, notice: t(".successfully_updated") }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: t(".successfully_destroyed") }
      format.json { head :no_content }
    end
  end

  # POST /cards/orc.json
  def ocr
    image_file = params[:image]
    image_file.open
    begin
      image = image_file.read
    ensure
      image_file.close
    end
    google_api = GoogleApi::ImageAnnotate.new(image)
    @texts = CardTextAnalyzer.new(google_api.get_text_blocks.summary&.text)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_card
    @card = Card.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def card_params
    params.require(:card).permit(:company_id, :name, :kana_name, :department, :position, :postcode, :address, :building, :tel, :cellular_phone, :fax, :mail, :front_image, :back_image, :qualification, :note)
  end
end

app/views/cards/_form.html.erb
<%= form_with(model: card,
              auto_init: true,
              local: true,
              class: "content-cards-form",
              builder: MdcFormHelper::MdcFormBuilder) do |form| %>
  <% if card.errors.any? %>
    <div class="res-error-explanation">
      <p class="mdc-typography--headline6 res-error-explanation__result">
        <%= t("errors.template.header", count: card.errors.count, model: Card.model_name.human) %>:
      </p>
      <ul class="res-error-explanation__message-list">
    <% card.errors.full_messages.each do |message| %>
        <li class="res-error-explanation__message-item"><%= message %></li>
    <% end %>
      </ul>
    </div>
  <% end %>
  <div class="res-field field-left">
    <%= form.image_field :front_image, max_height: 256, accept: "image/png, image/jpeg, image/gif" %>
    <%= form.image_field :back_image, max_height: 256, accept: "image/png, image/jpeg, image/gif" %><br />
    <%= mdc_switch nil, nil, true, label: t(".use_assistance"), id: "use-assistance", auto_init: true %>
  </div>
  <div class="res-field">
    <%= form.text_field :name, required: true, maxlength: 31, list: "all-list", autocomplete: "off" %>
  </div>
  <div class="res-field">
    <%= form.text_field :kana_name, required: true, maxlength: 63, autocomplete: "off" %>
  </div>
  <div class="res-field">
    <%= form.select :company_id, Company.order(:kana_name).map{|c| [c.short_name, c.id]}, { box: true }, { required: true, class: "field-company" } %>
  </div>
  <div class="res-field">
    <%= form.text_field :department, maxlength: 31, list: "all-list", autocomplete: "off" %>
    <%= form.text_field :position, maxlength: 31, list: "all-list", autocomplete: "off" %>
  </div>
  <div class="res-field">
    <%= form.text_field :qualification, maxlength: 255, list: "all-list", autocomplete: "off" %>
  </div>
  <div class="res-field">
    <%= form.text_field :postcode, maxlength: 8, pattern: "\\d{3}-\\d{4}", class: "field-postcode", list: "post-code-list", autocomplete: "off" %>
    <%= form.text_field :address, maxlength: 127, list: "address-list", class: "field-address", autocomplete: "off" %>
    <%= form.text_field :building, maxlength: 127, list: "all-list", autocomplete: "off" %>
  </div>
  <div class="res-field">
    <%= form.text_field :tel, maxlength: 15, pattern: "0[\\d\\-]{11,14}", class: "field-tel", list: "phone-list", autocomplete: "off" %>
    <%= form.text_field :cellular_phone, maxlength: 15, pattern: "0[\\d\\-]{11,14}", list: "phone-list", autocomplete: "off" %>
    <%= form.text_field :fax, maxlength: 15, pattern: "0[\\d\\-]{11,14}", list: "phone-list", autocomplete: "off" %>
  </div>
  <div class="res-field">
    <%= form.text_field :mail, maxlength: 255, pattern: "[\\w+\\-.]+@[a-z\\d\\-.]+\\.[a-z]+", class: "field-mail", list: "mail-list", autocomplete: "off" %>
  </div>
  <div class="res-field">
    <%= form.text_field :note, maxlength: 255, autocomplete: "off" %>
  </div>
  <div class="res-actions">
    <%= mdc_link_to t("helpers.button.cancel"), {action: :index}, auto_init: true %>
    <%= form.submit raised: true, class: "res-button--raised--secondary" %>
  </div>
  <datalist id="all-list"></datalist>
  <datalist id="post-code-list"></datalist>
  <datalist id="address-list"></datalist>
  <datalist id="phone-list"></datalist>
  <datalist id="mail-list"></datalist>
  <div class="mdc-dialog" role="alertdialog" aria-model="true" aria-labelledy="confirm-title" aria-desribedby="confrim-content" id="confirm" data-mdc-auto-init="MDCDialog">
    <div class="mdc-dialog__container">
      <div class="mdc-dialog__surface">
        <h3 class="mdc-dialog__title" id="confirm-title"><%= t("api.postcode.do_you_want_to_overwrite_address") %></h3>
        <div class="mdc-dialog__content" id="confirm-content"><%= t("api.postcode.address_information_obtained_html", obtaind_class: "obtained-address") %></div>
        <footer class="mdc-dialog__actions">
          <button type="button" class="mdc-button mdc-dialog__button" data-mdc-dialog-action="close">
            <span class="mdc-button__label"><%= t("helpers.button.no") %></span>
          </button>
          <button type="button" class="mdc-button mdc-dialog__button mdc-dialog__button--default" data-mdc-dialog-action="accept">
            <span class="mdc-button__label"><%= t("helpers.button.yes") %></span>
          </button>
        </footer>
      </div>
    </div>
    <div class="mdc-dialog__scrim"></div>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h2 class="mdc-typography--headline5 res-content-title"><%= t(".edit_card")%></h2>

<div class="res-form-container">
  <%= render 'form', card: @card %>
</div>

app/views/cards/index.html.erb
<h2 class="mdc-typography--headline5 res-content-title"><%= t(".business_cards")%></h2>

<div class="res-content content-cards">
  <aside class="res-nav">
    <nav class="res-nav__nav">
      <div class="mdc-typography--subtitle1 res-nav__title mdc-list">
        <div class="mdc-list-item__graphic">
          <%= mdc_check_box_tag "comp-list-head", "ct", true, auto_init: true, id: nil, class: "res-cards-company-header-checkbox res-cards-company-checkbox" %>
        </div>
        <%= Company.model_name.human %>
      </div>
      <ul class="mdc-list mdc-list--dense res-company-list">
      <% @companies.each do |company| %>
        <li class="mdc-list-item res-item-company" data-mdc-auto-init="MDCRipple">
          <div class="mdc-list-item__graphic">
            <%= mdc_check_box_tag "comp#{company.id}", company.id, true, auto_init: true, id: nil, class: "res-cards-company-checkbox" %>
          </div><%= company.short_name %>
        </li>
      <% end %>
      </ul>
    </nav>
  </aside>
  <div class="res-content-area">
    <div class="mdc-list-group res-content-list res-cards-list">
      <%= mdc_divided_list @cards, :kana_name, :kana, avatar_list: true do |card| %>
        <li class="mdc-list-item res-card-item" data-card-url="<%= card_path(card, format: :json) %>" data-card-id="<%= card.id %>" data-company-id="<%= card.company.id %>">
        <% if card.company.logo_image.present? %>
          <%= base64_image_tag card.company.logo_image, height: 36, alt: "logo", title: card.company.omit_name, class: "mdc-list-item__graphic res-company-item__logo" %>
        <% else %>
          <i class="material-icons mdc-list-item__graphic res-company-item__logo" aria-hidden="true" title="<%= card.company.omit_name %>">business</i>
        <% end %>
          <%= card.name %>
          <span class="mdc-list-item__meta"><%= card.department %> <%= card.position %></span>
        </li>
      <% end %>
    </div>
  </div>
  <div class="mdc-card res-card res-cards-card" style="display:none">
    <div class="mdc-card__media res-card__media">
      <div class="mdc-card__media-content">
        <div class="res-card__media__icon-button-area">
          <%= mdc_icon_button_tag "delete", title: "delete", class: "res-cards-card-delete" %>
          <%= mdc_icon_button_tag "close", title: "close", class: "res-cards-card-close" %>
        </div>
        <div class="res-card__media__title">
          <span class="mdc-typography--headline6 res-card-info__name"></span>
          <span class="mdc-typography--caption res-card__media__caption res-card-info__qualification"></span>
        </div>
      </div>
      <%= mdc_fab_link_to "edit", "#", mini: true, class: "res-card__fab", label: t(".edit_card"), title: t(".edit_card") %>
    </div>
    <div class="res-card__main">
      <ul class="mdc-list mdc-list--two-line mdc-list--non-interactive res-list--content">
        <li class="mdc-list-item res-cards-content__name">
          <i class="material-icons mdc-list-item__graphic" title="<%= Card.human_attribute_name(:company) %>" aria-hidden="true">business</i>
          <span class="mdc-list-item__text">
            <span class="res-card-info__company-name--label"></span><a class="res-list-item__link res-card-info__company-name--link" href="#" target="_blank"></a>
            <span class="mdc-list-item__secondary-text res-card-info__department"></span>
          </span>
        </li>
        <li class="mdc-list-item">
          <i class="material-icons mdc-list-item__graphic" title="<%= Card.human_attribute_name(:address) %>" aria-hidden="true">place</i>
          <a class="res-list-item__link res-card-info__post-address-building" href="#" target="_blank"></a>
        </li>
        <li class="mdc-list-item">
          <i class="material-icons mdc-list-item__graphic" title="<%= Card.human_attribute_name(:tel) %>" aria-hidden="true">phone</i>
          <a class="res-list-item__link res-card-info__tel" href="#" target="_blank"></a>
        </li>
        <li class="mdc-list-item">
          <i class="material-icons mdc-list-item__graphic" title="<%= Card.human_attribute_name(:cellular_phone) %>" aria-hidden="true">smartphone</i>
          <a class="res-list-item__link res-card-info__cellular-phone" href="#" target="_blank"></a>
        </li>
        <li class="mdc-list-item">
          <i class="material-icons mdc-list-item__graphic" title="<%= Card.human_attribute_name(:fax) %>" aria-hidden="true">print</i>
          <span class="res-card-info__fax"></span>
        </li>
        <li class="mdc-list-item">
          <i class="material-icons mdc-list-item__graphic" title="<%= Card.human_attribute_name(:mail) %>" aria-hidden="true">email</i>
          <a class="res-list-item__link res-card-info__mail" href="#" target="_blank"></a>
        </li>
        <li class="mdc-list-item">
          <i class="material-icons mdc-list-item__graphic" title="<%= Card.human_attribute_name(:note) %>" aria-hidden="true">note</i>
          <span class="res-card-info__note"></span>
        </li>
      </ul>
    </div>
  </div>

  <%= mdc_fab_link_to "add", {action: :new}, class: "res-add-fab res-card-add-button", label: t(".create_card"), title: t(".create_card") %>

  <div class="mdc-snackbar res-cards-snackbar" data-mdc-auto-init="MDCSnackbar">
    <div class="mdc-snackbar__surface">
      <div class="mdc-snackbar__label res-cards-result" role="status" aria-live="polite"><%= notice %></div>
      <div class="mdc-snackbar__actions">
        <button type="button" class="mdc-button mdc-snackbar__action"></button>
      </div>
    </div>
  </div>
</div>

app/views/cards/new.html.erb
<h2 class="mdc-typography--headline5 res-content-title"><%= t(".create_card")%></h2>

<div class="res-form-container">
  <%= render 'form', card: @card %>
</div>